In [1]:
import pandas as pd
import numpy as np

import os

In [2]:
PROCESSED_DIR = '../data/processed/'
PROCESSED_FILENAME = "usdjpy-bar-2020-01-01-2024-12-31_processed.pkl"
PROCESSED_FILE_PATH = os.path.join(PROCESSED_DIR, PROCESSED_FILENAME)

In [3]:
df = pd.read_pickle(PROCESSED_FILE_PATH)
df.head()

timestamp      open      high       low     close        volume  \
1 2020-01-01 22:01:00  108.7570  108.7590  108.7495  108.7495  13300.000012   
2 2020-01-01 22:02:00  108.7495  108.7535  108.7495  108.7535   4500.000000   
3 2020-01-01 22:03:00  108.7540  108.7555  108.7535  108.7555  10490.000010   
4 2020-01-01 22:04:00  108.7575  108.7650  108.7555  108.7650  11600.000024   
5 2020-01-01 22:05:00  108.7700  108.7700  108.7690  108.7700   1059.999987   

   time_group  close_delta  close_return close_direction  prob_down  \
1           1      -0.0095     -0.000087            down        1.0   
2           1       0.0040      0.000037              up        0.0   
3           1       0.0020      0.000018            flat        0.0   
4           1       0.0095      0.000087              up        0.0   
5           1       0.0050      0.000046              up        0.0   

   prob_flat  prob_up  label  
1        0.0      0.0      0  
2        0.0      1.0      2  
3        1.0      0.0      1  
4        0.0      1.0      2  
5        0.0      1.0      2

In [4]:
df.describe()

timestamp          open          high  \
count                        1818676  1.818676e+06  1.818676e+06   
mean   2022-07-05 13:20:55.965527552  1.281896e+02  1.282000e+02   
min              2020-01-01 22:01:00  1.012020e+02  1.013380e+02   
25%              2021-04-01 18:33:45  1.094595e+02  1.094650e+02   
50%              2022-07-11 20:03:30  1.312150e+02  1.312340e+02   
75%              2023-10-04 07:22:15  1.456610e+02  1.456740e+02   
max              2024-12-30 23:59:00  1.619500e+02  1.619510e+02   
std                              NaN  1.839441e+01  1.839714e+01   

                low         close        volume    time_group   close_delta  \
count  1.818676e+06  1.818676e+06  1.818676e+06  1.818676e+06  1.818676e+06   
mean   1.281792e+02  1.281896e+02  4.311489e+05  4.203974e+03  3.065142e-05   
min    1.011820e+02  1.012045e+02  0.000000e+00  1.000000e+00 -2.065000e+00   
25%    1.094540e+02  1.094600e+02  1.180375e+05  1.847000e+03 -7.000000e-03   
50%    1.311990e+02  1.312150e+02  2.726000e+05  4.956000e+03  0.000000e+00   
75%    1.456491e+02  1.456615e+02  5.858400e+05  6.143000e+03  7.500000e-03   
max    1.619435e+02  1.619495e+02  1.226455e+08  7.375000e+03  1.579500e+00   
std    1.839161e+01  1.839442e+01  5.050698e+05  2.341641e+03  2.094446e-02   

       close_return     prob_down     prob_flat       prob_up         label  
count  1.818676e+06  1.818676e+06  1.818676e+06  1.818676e+06  1.818676e+06  
mean   2.461495e-07  3.382592e-01  3.180924e-01  3.436483e-01  1.005389e+00  
min   -1.380804e-02  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  
25%   -5.705061e-05  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00  
75%    5.846136e-05  1.000000e+00  1.000000e+00  1.000000e+00  2.000000e+00  
max    1.228753e-02  1.000000e+00  1.000000e+00  1.000000e+00  2.000000e+00  
std    1.558500e-04  4.731174e-01  4.657357e-01  4.749255e-01  8.257596e-01

In [5]:
GROUP_COL = 'time_group'
SEQ_LEN = 30
HORIZON = 0

In [6]:
def get_sequence_start_indices(df, sequence_length=30, horizon=1, stride=1, group_col='time_group'):
    indices = []
    group_to_indices = {}
    
    for idx, group in zip(df.index, df[group_col]):
        group_to_indices.setdefault(group, []).append(idx)

    for group, idxs in group_to_indices.items():
        if len(idxs) < sequence_length + horizon:
            continue

        idxs = sorted(idxs)
        max_start = len(idxs) - sequence_length - horizon + 1
        for start in range(0, max_start, stride):
            indices.append(idxs[start])

    return indices


In [13]:
IDs = get_sequence_start_indices(
    df, 
    sequence_length=SEQ_LEN,
    horizon=HORIZON,
    stride=5,
    group_col='time_group',
)

In [14]:
df.loc[IDs[-1]: IDs[-1] + SEQ_LEN - 1]

timestamp      open      high       low     close  \
1860606 2024-12-30 23:26:00  157.0300  157.0320  157.0300  157.0300   
1860607 2024-12-30 23:27:00  157.0305  157.0305  157.0250  157.0250   
1860608 2024-12-30 23:28:00  157.0250  157.0300  157.0245  157.0250   
1860609 2024-12-30 23:29:00  157.0250  157.0305  157.0250  157.0270   
1860610 2024-12-30 23:30:00  157.0280  157.0320  157.0250  157.0295   
1860611 2024-12-30 23:31:00  157.0280  157.0520  157.0205  157.0500   
1860612 2024-12-30 23:32:00  157.0495  157.0495  157.0345  157.0360   
1860613 2024-12-30 23:33:00  157.0355  157.0370  157.0290  157.0335   
1860614 2024-12-30 23:34:00  157.0325  157.0325  156.9870  157.0185   
1860615 2024-12-30 23:35:00  157.0160  157.0160  156.9625  156.9690   
1860616 2024-12-30 23:36:00  156.9675  157.0080  156.9610  156.9745   
1860617 2024-12-30 23:37:00  156.9740  156.9965  156.9725  156.9955   
1860618 2024-12-30 23:38:00  156.9955  157.0020  156.9945  157.0010   
1860619 2024-12-30 23:39:00  157.0010  157.0085  156.9950  157.0075   
1860620 2024-12-30 23:40:00  157.0075  157.0240  157.0050  157.0235   
1860621 2024-12-30 23:41:00  157.0230  157.0305  157.0190  157.0295   
1860622 2024-12-30 23:42:00  157.0280  157.0345  157.0230  157.0345   
1860623 2024-12-30 23:43:00  157.0320  157.0330  157.0285  157.0310   
1860624 2024-12-30 23:44:00  157.0305  157.0345  157.0275  157.0335   
1860625 2024-12-30 23:45:00  157.0330  157.0410  157.0320  157.0330   
1860626 2024-12-30 23:46:00  157.0310  157.0310  156.9830  156.9955   
1860627 2024-12-30 23:47:00  156.9925  156.9975  156.9850  156.9855   
1860628 2024-12-30 23:48:00  156.9850  156.9985  156.9850  156.9950   
1860629 2024-12-30 23:49:00  156.9935  156.9955  156.9920  156.9955   
1860630 2024-12-30 23:50:00  156.9950  156.9960  156.9945  156.9950   
1860631 2024-12-30 23:51:00  156.9945  157.0020  156.9785  156.9970   
1860632 2024-12-30 23:52:00  156.9965  157.0030  156.9960  156.9975   
1860633 2024-12-30 23:53:00  156.9980  156.9990  156.9975  156.9985   
1860634 2024-12-30 23:54:00  156.9975  157.0125  156.9960  157.0125   
1860635 2024-12-30 23:55:00  157.0100  157.0110  157.0075  157.0080   

                volume  time_group  close_delta  close_return close_direction  \
1860606   36450.000405        7375      -0.0015     -0.000010            flat   
1860607   25049.999952        7375      -0.0050     -0.000032            down   
1860608  130050.000191        7375       0.0000      0.000000            flat   
1860609  133620.002031        7375       0.0020      0.000013            flat   
1860610  325200.001121        7375       0.0025      0.000016            flat   
1860611  277389.999866        7375       0.0205      0.000131              up   
1860612  266069.999933        7375      -0.0140     -0.000089            down   
1860613  148949.999571        7375      -0.0025     -0.000016            flat   
1860614  320040.005445        7375      -0.0150     -0.000096            down   
1860615  287070.008516        7375      -0.0495     -0.000315            down   
1860616  690720.003605        7375       0.0055      0.000035              up   
1860617  184260.001540        7375       0.0210      0.000134              up   
1860618  103620.001674        7375       0.0055      0.000035              up   
1860619  337080.002427        7375       0.0065      0.000041              up   
1860620  508770.000696        7375       0.0160      0.000102              up   
1860621  342899.998665        7375       0.0060      0.000038              up   
1860622  550259.997368        7375       0.0050      0.000032              up   
1860623  331619.999051        7375      -0.0035     -0.000022            flat   
1860624  224219.999909        7375       0.0025      0.000016            flat   
1860625  194879.999399        7375      -0.0005     -0.000003            flat   
1860626  287730.002761        7375      -0.0375     -0.000239            down   
1860627  267900.000334        7375

In [15]:
import torch
from torch.utils.data import Dataset
import numpy as np

class ForexDataset(Dataset):
    """Dataset for sequence classification/forecasting with multi-step horizon."""

    def __init__(self, data, IDs, sequence_length, horizon, features, target):
        self.data = data
        self.IDs = IDs
        self.sequence_length = sequence_length
        self.horizon = horizon
        self.feature_data = data[features]
        self.target_data = data[target]
    def __len__(self):
        return len(self.IDs)

    def __getitem__(self, idx):
        i = self.IDs[idx]
        
        # Extract feature sequence
        X = self.feature_data.loc[i:i + self.sequence_length].values

        # Extract target(s)
        y = self.target_data.loc[i+self.sequence_length + self.horizon - 1].values

        return torch.from_numpy(X), torch.from_numpy(y), i


In [18]:
fx_dataset = ForexDataset(
    data=df, 
    IDs=IDs,
    sequence_length=SEQ_LEN, 
    horizon=HORIZON, 
    features=['close_return'],
    target=['close_return'],
)
    

In [17]:
fx_dataset[0]

(tensor([[-8.7349e-05],
         [ 3.6782e-05],
         [ 1.8390e-05],
         [ 8.7352e-05],
         [ 4.5971e-05],
         [-1.1952e-04],
         [ 4.5974e-06],
         [-2.7584e-05],
         [-7.8158e-05],
         [-9.1957e-06],
         [-4.5979e-05],
         [ 1.6093e-04],
         [-9.1948e-05],
         [-2.2989e-05],
         [ 2.2990e-05],
         [-4.5978e-06],
         [-9.1957e-06],
         [-8.6440e-04],
         [ 3.5894e-04],
         [ 1.3801e-05],
         [ 5.0601e-05],
         [-4.5999e-06],
         [ 1.6560e-04],
         [ 5.0591e-05],
         [-1.0578e-04],
         [ 4.5994e-06],
         [-4.5994e-06],
         [ 1.7478e-04],
         [-1.4256e-04],
         [-4.5993e-06],
         [-4.5993e-06]], dtype=torch.float64),
 tensor([-4.5993e-06], dtype=torch.float64),
 1)

In [135]:
df.loc[51:82, ['close_return']]

close_return
51     -0.000009
52      0.000000
53      0.000005
54     -0.000005
55     -0.000009
56      0.000023
57     -0.000005
58      0.000014
59      0.000005
60     -0.000570
61      0.000018
62     -0.000193
63      0.000028
64     -0.000028
65     -0.000014
66      0.000051
67     -0.000005
68     -0.000005
69      0.000322
70      0.000023
71      0.000014
72      0.000074
73     -0.000009
74      0.000005
75     -0.000069
76     -0.000037
77     -0.000032
78      0.000083
79      0.000009
80      0.000023
81      0.000175
82     -0.000078

In [105]:
fx_dataset = ForexClassificationDataset(
    data=df, 
    IDs=IDs,
    sequence_length=SEQ_LEN, 
    horizon=1, 
    features=['close_return'],
    target=['close_return'],
)
    

In [106]:
fx_dataset[5]

(tensor([[ 4.5994e-06],
         [-4.5994e-06],
         [ 1.7478e-04],
         [-1.4256e-04],
         [-4.5993e-06],
         [-4.5993e-06],
         [-3.2195e-05],
         [ 0.0000e+00],
         [ 9.1989e-06],
         [-1.3798e-04],
         [-1.2420e-04],
         [ 4.6006e-06],
         [ 4.6006e-06],
         [-1.3802e-05],
         [ 1.3802e-05],
         [-2.3003e-05],
         [ 1.8403e-05],
         [-4.6006e-06],
         [ 9.2012e-06],
         [ 3.2204e-05],
         [ 1.8402e-05],
         [ 0.0000e+00],
         [ 9.2007e-06],
         [ 0.0000e+00],
         [ 1.8401e-05],
         [-9.2004e-06],
         [ 0.0000e+00],
         [ 4.6003e-06],
         [-4.6002e-06],
         [-9.2005e-06]]),
 tensor([2.3002e-05]),
 26)

## Good old train / test split

In [79]:
from sklearn.model_selection import train_test_split

train_idx, val_idx = train_test_split(
    IDs,
    test_size=0.2,
    shuffle=True,
    random_state=42
)


In [80]:
train_dataset = ForexClassificationDataset(
    data=df, 
    IDs=train_idx,
    sequence_length=SEQ_LEN, 
    horizon=HORIZON, 
    features=['close_return'],
    target=['prob_down', 'prob_flat', 'prob_up'],
)

val_dataset = ForexClassificationDataset(
    data=df, 
    IDs=val_idx,
    sequence_length=SEQ_LEN, 
    horizon=HORIZON, 
    features=['close_return'],
    target=['prob_down', 'prob_flat', 'prob_up'],
)

In [81]:
len(train_dataset), len(val_dataset)

(278025, 69507)

In [85]:
train_dataset[-1]

(tensor([[-3.9572e-05],
         [-1.7588e-04],
         [ 4.8376e-05],
         [-8.7952e-06],
         [ 4.3976e-06],
         [ 7.9157e-05],
         [-8.3548e-05],
         [ 4.3976e-06],
         [ 4.8374e-05],
         [-4.3974e-06],
         [ 7.0358e-05],
         [-1.1432e-04],
         [ 4.3976e-05],
         [-8.7948e-06],
         [-3.9577e-05],
         [ 1.8470e-04],
         [-4.3968e-05],
         [-3.9573e-05],
         [ 1.0993e-04],
         [-7.9140e-05],
         [ 3.5176e-05],
         [-7.9144e-05],
         [ 5.7164e-05],
         [-7.0352e-05],
         [ 5.7165e-05],
         [ 1.4071e-04],
         [ 8.7928e-06],
         [-4.3964e-05],
         [ 3.5173e-05],
         [ 0.0000e+00]]),
 tensor([[0., 0., 1.]]),
 678787)

## Stratified Shuffle

In [ ]:
valid_start_idxs[:5]

In [ ]:
target_indices = np.array(valid_start_idxs) + SEQ_LEN + HORIZON - 1


In [ ]:
target_indices

In [ ]:
from sklearn.model_selection import StratifiedShuffleSplit
import numpy as np

def get_stratified_split(df, valid_start_indices, sequence_length, horizon, target_col, test_size=0.2):
    valid_start_indices = np.array(valid_start_indices)  # ensure array

    target_indices = valid_start_indices + sequence_length + horizon - 1
    labels = df.loc[target_indices, target_col].values  # get labels efficiently

    splitter = StratifiedShuffleSplit(n_splits=1, test_size=test_size, random_state=42)
    train_idx, val_idx = next(splitter.split(valid_start_indices, labels))

    train_start_indices = valid_start_indices[train_idx]
    val_start_indices = valid_start_indices[val_idx]

    return train_start_indices.tolist(), val_start_indices.tolist()


In [ ]:
train_idx, test_idx = get_stratified_split(
    df,
    valid_start_indices=valid_start_idxs,
    sequence_length=SEQ_LEN,
    horizon=HORIZON,
    target_col='label'
)

In [ ]:
len(train_idx), len(test_idx)