In [3]:
import sys
sys.path.append("..")
from pathlib import Path
# Reload modules in /src/ when changed
%load_ext autoreload
%autoreload 2

from fxml.data.normalize_data import denorm

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# plt.rcParams["figure.figsize"] = (12, 2)
import seaborn as sns
sns.set(style="ticks", palette="tab10")

In [4]:
from hydra import compose, initialize
from omegaconf import OmegaConf

# global initialization
initialize(version_base=None, config_path="../configs", job_name="test_app")
cfg = compose(config_name="preprocessing")
print(OmegaConf.to_yaml(cfg))

data:
  train_data_path: data/processed/USDJPY-15m-20210101-20231231_FEATURES.pkl
  test_data_path: data/processed/USDJPY-15m-20240101-20241231_FEATURES.pkl
minutes:
- 15
date:
- from: 20210101
  to: 20231231
- from: 20240101
  to: 20241231
symbol:
  raw_path: data/raw/usdjpy-tick-2021-01-01-2024-12-31.csv
  symbol: USDJPY
features:
  returns:
    price_cols:
    - close
    d_value: 0.5
  technical_indicators:
    rv_windows:
    - 5
    - 15
    - 50
    ema_windows:
    - 5
    - 9
    - 20
    - 24
    - 36
    - 50
    - 100
    atr_windows:
    - 14
    - 60
    - 120
    adx_windows:
    - 14
    rsi_windows:
    - 14
    - 25
    - 50
    bb_windows:
    - 5
    - 10
    - 15
    - 20
    macd:
    - fast: 8
      slow: 17
      signal: 9
    - fast: 12
      slow: 26
      signal: 9
scaler:
  open:
    type: minmax
  high:
    type: minmax
  low:
    type: minmax
  close:
    type: minmax
  volume:
    type: robust
  spread:
    type: std
  tick:
    type: robust
  close_pct_r

In [5]:
root_dir = Path('..')
train_df = pd.read_pickle(root_dir / Path(cfg.data.train_data_path))
test_df = pd.read_pickle(root_dir / Path(cfg.data.test_data_path))

In [6]:
close = test_df[['close']]

In [7]:
import joblib

In [8]:
scaler = joblib.load('../data/processed/scalers/USDJPY-15m-20210101-20231231_FEATURES/close_std.pkl')

In [18]:
norm_df = pd.read_pickle('../data/processed/USDJPY-15m-20210101-20231231_FEATURES_NORM.pkl')

In [9]:
close_norm = scaler.transform(close)

In [10]:
close_norm

array([[1.24612671],
       [1.24585468],
       [1.24401843],
       ...,
       [2.00235351],
       [2.00279557],
       [2.00109534]], shape=(23982, 1))

In [11]:
close.values

array([[145.9075],
       [145.9035],
       [145.8765],
       ...,
       [157.027 ],
       [157.0335],
       [157.0085]], shape=(23982, 1))

In [12]:
scaler.inverse_transform(close_norm)

array([[145.9075],
       [145.9035],
       [145.8765],
       ...,
       [157.027 ],
       [157.0335],
       [157.0085]], shape=(23982, 1))

In [13]:
import torch

In [14]:
prediction = torch.randn(60,1).numpy()
prediction

array([[-1.0813231e+00],
       [-4.9682149e-01],
       [-3.0774313e-01],
       [ 7.4321651e-01],
       [-3.0063036e-01],
       [-5.8762378e-01],
       [-2.5618669e-01],
       [-6.5953732e-02],
       [ 6.1271483e-01],
       [-1.7129234e+00],
       [ 1.0640193e+00],
       [ 7.2805083e-01],
       [ 1.7563511e+00],
       [-9.2010401e-02],
       [-7.7365857e-01],
       [-9.8849338e-01],
       [-1.5306255e-01],
       [-6.6587621e-01],
       [-7.4241716e-01],
       [-6.1302447e-01],
       [ 3.5922688e-01],
       [ 1.6807005e+00],
       [-3.4766100e-02],
       [ 7.7303338e-01],
       [-3.3725902e-01],
       [ 1.1653847e+00],
       [ 1.8261485e+00],
       [ 5.0103861e-01],
       [ 7.3159143e-04],
       [ 1.5820539e+00],
       [ 2.4831827e-01],
       [-5.0377846e-01],
       [-9.4253230e-01],
       [-1.7832384e-01],
       [-2.4073124e+00],
       [ 8.4789254e-02],
       [ 1.6236147e+00],
       [ 6.4903975e-01],
       [ 6.6748631e-01],
       [-8.0458665e-01],


In [15]:
scaler.inverse_transform(prediction)

array([[111.68486 ],
       [120.27933 ],
       [123.05952 ],
       [138.51274 ],
       [123.1641  ],
       [118.944176],
       [123.817604],
       [126.61477 ],
       [136.59386 ],
       [102.39786 ],
       [143.22981 ],
       [138.28975 ],
       [153.4098  ],
       [126.231636],
       [116.20873 ],
       [113.04982 ],
       [125.33393 ],
       [117.79356 ],
       [116.668106],
       [118.57069 ],
       [132.8666  ],
       [152.29744 ],
       [127.07335 ],
       [138.95117 ],
       [122.62552 ],
       [144.72028 ],
       [154.4361  ],
       [134.95178 ],
       [127.59531 ],
       [150.84695 ],
       [131.23581 ],
       [120.17703 ],
       [113.725624],
       [124.96249 ],
       [ 92.187614],
       [128.83128 ],
       [151.45805 ],
       [137.12798 ],
       [137.39922 ],
       [115.75397 ],
       [126.627205],
       [114.74669 ],
       [113.182144],
       [118.44739 ],
       [124.4068  ],
       [138.68607 ],
       [127.95994 ],
       [148.3