In [4]:
import sys
sys.path.append("..")
from pathlib import Path
# Reload modules in /src/ when changed
%load_ext autoreload
%autoreload 2

from fxml.data.normalize_data import denorm

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# plt.rcParams["figure.figsize"] = (12, 2)
import seaborn as sns
sns.set(style="ticks", palette="tab10")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
from hydra import compose, initialize
from omegaconf import OmegaConf

# global initialization
initialize(version_base=None, config_path="../configs", job_name="test_app")
cfg = compose(config_name="preprocessing")
print(OmegaConf.to_yaml(cfg))

data:
  train_data_path: data/processed/USDJPY-15m-20210101-20231231_FEATURES.pkl
  test_data_path: data/processed/USDJPY-15m-20240101-20241231_FEATURES.pkl
minutes:
- 15
date:
- from: 20210101
  to: 20231231
- from: 20240101
  to: 20241231
symbol:
  raw_path: data/raw/usdjpy-tick-2021-01-01-2024-12-31.csv
  symbol: USDJPY
features:
  returns:
    price_cols:
    - close
    d_value: 0.5
  technical_indicators:
    rv_windows:
    - 5
    - 15
    - 50
    ema_windows:
    - 5
    - 9
    - 20
    - 24
    - 36
    - 50
    - 100
    atr_windows:
    - 14
    - 60
    - 120
    adx_windows:
    - 14
    rsi_windows:
    - 14
    - 25
    - 50
    bb_windows:
    - 5
    - 10
    - 15
    - 20
    macd:
    - fast: 8
      slow: 17
      signal: 9
    - fast: 12
      slow: 26
      signal: 9
scaler:
  open:
    type: std
  high:
    type: std
  low:
    type: std
  close:
    type: std
  volume:
    type: log
  spread:
    type: robust
  tick:
    type: none
  close_pct_return:
    typ

In [8]:
root_dir = Path('..')
train_df = pd.read_pickle(root_dir / Path(cfg.data.train_data_path))
test_df = pd.read_pickle(root_dir / Path(cfg.data.test_data_path))

In [13]:
close = test_df[['close']]

In [14]:
import joblib

In [15]:
scaler = joblib.load('../data/processed/scalers/USDJPY-15m-20210101-20231231_FEATURES/close_std.pkl')

In [16]:
close_norm = scaler.transform(close)

In [17]:
close_norm

array([[1.24612671],
       [1.24585468],
       [1.24401843],
       ...,
       [2.00235351],
       [2.00279557],
       [2.00109534]], shape=(23982, 1))

In [19]:
close.values

array([[145.9075],
       [145.9035],
       [145.8765],
       ...,
       [157.027 ],
       [157.0335],
       [157.0085]], shape=(23982, 1))

In [18]:
scaler.inverse_transform(close_norm)

array([[145.9075],
       [145.9035],
       [145.8765],
       ...,
       [157.027 ],
       [157.0335],
       [157.0085]], shape=(23982, 1))

In [20]:
import torch

In [25]:
prediction = torch.randn(60,1).numpy()
prediction

array([[-1.298052  ],
       [ 0.7539047 ],
       [-1.6264145 ],
       [ 0.69699067],
       [-0.18015198],
       [-0.6553043 ],
       [-0.6728345 ],
       [ 0.29858482],
       [-0.9717607 ],
       [-0.8265001 ],
       [ 0.1803432 ],
       [-0.5750843 ],
       [ 2.3820727 ],
       [ 0.6361271 ],
       [ 0.04915798],
       [-0.95311725],
       [ 0.8900457 ],
       [ 1.2229624 ],
       [ 1.4366989 ],
       [-0.74636394],
       [-0.76319706],
       [-0.14173716],
       [ 1.6074793 ],
       [ 0.8408816 ],
       [-1.3564382 ],
       [-0.16682486],
       [ 0.26866776],
       [ 1.0550576 ],
       [ 0.89408094],
       [-0.03116335],
       [ 0.8002359 ],
       [ 0.62847686],
       [-0.05029252],
       [-1.2354543 ],
       [-0.50512   ],
       [ 0.3899003 ],
       [ 1.2130878 ],
       [ 1.0565518 ],
       [ 0.57114226],
       [ 0.17081788],
       [ 0.23477246],
       [-1.003273  ],
       [ 1.8347659 ],
       [-0.67718136],
       [ 0.4803116 ],
       [ 0

In [26]:
scaler.inverse_transform(prediction)

array([[108.49809 ],
       [138.6699  ],
       [103.669876],
       [137.83305 ],
       [124.93561 ],
       [117.949005],
       [117.691246],
       [131.97491 ],
       [113.29585 ],
       [115.431755],
       [130.2363  ],
       [119.128555],
       [162.61037 ],
       [136.93811 ],
       [128.30736 ],
       [113.569984],
       [140.6717  ],
       [145.5669  ],
       [148.70966 ],
       [116.61007 ],
       [116.36256 ],
       [125.50046 ],
       [151.2208  ],
       [139.9488  ],
       [107.63959 ],
       [125.13157 ],
       [131.53502 ],
       [143.09804 ],
       [140.73105 ],
       [127.12633 ],
       [139.35115 ],
       [136.82562 ],
       [126.845055],
       [109.418526],
       [120.1573  ],
       [133.31761 ],
       [145.42169 ],
       [143.12001 ],
       [135.98257 ],
       [130.09624 ],
       [131.03662 ],
       [112.832504],
       [154.5628  ],
       [117.62733 ],
       [134.64702 ],
       [136.24036 ],
       [138.9299  ],
       [109.9